
const ParseUtils = require('./utils.js')

let basic_ex_colors = 
`
black 	#000000 	
silver 	#c0c0c0 	
gray 	#808080 	
white 	#ffffff 	
maroon 	#800000 	
red 	#ff0000 	
purple 	#800080 	
fuchsia #ff00ff 	
green 	#008000 	
lime 	#00ff00 	
olive 	#808000 	
yellow 	#ffff00 	
navy 	#000080 	
blue 	#0000ff 	
teal 	#008080 	
aqua 	#00ffff
aliceblue       #f0f8ff 	
antiquewhite 	#faebd7 	
aqua 	    #00ffff 	
aquamarine 	#7fffd4 	
azure 	#f0ffff 	
beige 	#f5f5dc 	
bisque 	#ffe4c4 	
black 	#000000 	
blanchedalmond 	#ffebcd 	
blue 	#0000ff 	
blueviolet 	#8a2be2 	
brown 	#a52a2a 	
burlywood 	#deb887 	
cadetblue 	#5f9ea0 	
chartreuse 	#7fff00 	
chocolate 	#d2691e 	
coral 	#ff7f50 	
cornflowerblue 	#6495ed 	
cornsilk 	#fff8dc 	
crimson 	#dc143c 	
cyan        #00ffff
darkblue 	#00008b 	
darkcyan 	#008b8b 	
darkgoldenrod 	#b8860b 	
darkgray 	#a9a9a9 	
darkgreen 	#006400 	
darkgrey 	#a9a9a9 	
darkkhaki 	#bdb76b 	
darkmagenta 	#8b008b 	
darkolivegreen 	#556b2f 	
darkorange 	#ff8c00 	
darkorchid 	#9932cc 	
darkred 	#8b0000 	
darksalmon 	#e9967a 	
darkseagreen 	#8fbc8f 	
darkslateblue 	#483d8b 	
darkslategray 	#2f4f4f 	
darkslategrey 	#2f4f4f 	
darkturquoise 	#00ced1 	
darkviolet 	#9400d3 	
deeppink 	#ff1493 	
deepskyblue 	#00bfff 	
dimgray 	#696969 	
dimgrey 	#696969 	
dodgerblue 	#1e90ff 	
firebrick 	#b22222 	
floralwhite 	#fffaf0 	
forestgreen 	#228b22 	
fuchsia 	#ff00ff 	
gainsboro 	#dcdcdc 	
ghostwhite 	#f8f8ff 	
gold 	#ffd700 	
goldenrod 	#daa520 	
gray 	#808080 	
green 	#008000 	
greenyellow 	#adff2f 	
grey 	#808080 (synonym of gray) 	
honeydew 	#f0fff0 	
hotpink 	#ff69b4 	
indianred 	#cd5c5c 	
indigo 	#4b0082 	
ivory 	#fffff0 	
khaki 	#f0e68c 	
lavender 	#e6e6fa 	
lavenderblush 	#fff0f5 	
lawngreen 	#7cfc00 	
lemonchiffon 	#fffacd 	
lightblue 	#add8e6 	
lightcoral 	#f08080 	
lightcyan 	#e0ffff 	
lightgoldenrodyellow 	#fafad2 	
lightgray 	#d3d3d3 	
lightgreen 	#90ee90 	
lightgrey 	#d3d3d3 	
lightpink 	#ffb6c1 	
lightsalmon 	#ffa07a 	
lightseagreen 	#20b2aa 	
lightskyblue 	#87cefa 	
lightslategray 	#778899 	
lightslategrey 	#778899 	
lightsteelblue 	#b0c4de 	
lightyellow 	#ffffe0 	
lime 	#00ff00 	
limegreen 	#32cd32 	
linen 	#faf0e6 	
magenta	#ff00ff
maroon 	#800000 	
mediumaquamarine 	#66cdaa 	
mediumblue 	#0000cd 	
mediumorchid 	#ba55d3 	
mediumpurple 	#9370db 	
mediumseagreen 	#3cb371 	
mediumslateblue 	#7b68ee 	
mediumspringgreen 	#00fa9a 	
mediumturquoise 	#48d1cc 	
mediumvioletred 	#c71585 	
midnightblue 	#191970 	
mintcream 	#f5fffa 	
mistyrose 	#ffe4e1 	
moccasin 	#ffe4b5 	
navajowhite 	#ffdead 	
navy 	#000080 	
oldlace 	#fdf5e6 	
olive 	#808000 	
olivedrab 	#6b8e23 	
orange 	#ffa500 	
orangered 	#ff4500 	
orchid 	#da70d6 	
palegoldenrod 	#eee8aa 	
palegreen 	#98fb98 	
paleturquoise 	#afeeee 	
palevioletred 	#db7093 	
papayawhip 	#ffefd5 	
peachpuff 	#ffdab9 	
peru 	#cd853f 	
pink 	#ffc0cb 	
plum 	#dda0dd 	
powderblue 	#b0e0e6 	
purple 	#800080 	
rebeccapurple 	#663399 	
red 	#ff0000 	
rosybrown 	#bc8f8f 	
royalblue 	#4169e1 	
saddlebrown 	#8b4513 	
salmon 	#fa8072 	
sandybrown 	#f4a460 	
seagreen 	#2e8b57 	
seashell 	#fff5ee 	
sienna 	#a0522d 	
silver 	#c0c0c0 	
skyblue 	#87ceeb 	
slateblue 	#6a5acd 	
slategray 	#708090 	
slategrey 	#708090 	
snow 	#fffafa 	
springgreen 	#00ff7f 	
steelblue 	#4682b4 	
tan 	#d2b48c 	
teal 	#008080 	
thistle 	#d8bfd8 	
tomato 	#ff6347
transparent 	#0000000
turquoise 	#40e0d0 	
violet 	#ee82ee 	
wheat 	#f5deb3 	
white 	#ffffff 	
whitesmoke 	#f5f5f5
yellow 	#ffff00 	
yellowgreen 	#9acd32
`

let g_color_names = (() => {
    let clines = basic_ex_colors.split('\n')
    let all_names = []
    for ( let line of clines ) {
        line = line.trim()
        if ( line.length ) {
            line = line.replace(/\s+/g,' ')
            line = line.split(' ')
            let name = line[0].trim()
            if ( all_names.indexOf(name) < 0 ) {
                all_names.push(name)
            }
        }
    }
    return all_names
})()




//
function vars_to_text(all_vars) {
    let output = ""
    for ( let [ky,val] of Object.entries(all_vars) ) {
        output += `\t${ky} : ${val};` + "\n"
    }
    return output
}


/**
 * 
 * (generated by AI)
 * 
 * @param {string} originalString
 * @param {number} start
 * @param {number} deleteCount
 * @param {string} newSubstr
 * @returns {string}
 */
function stringSplice(originalString, start, deleteCount, newSubstr = '') {
    // 1. Convert the string to an array of characters
    // Using Array.from() is more Unicode-aware than split('')
    const arr = Array.from(originalString);

    // 2. Use the standard Array.prototype.splice() method
    // start: Index at which to start changing the array
    // deleteCount: Number of elements to remove
    // newSubstr: The elements to add, if any (must be spread if it's a string)
    if (newSubstr !== '') {
        arr.splice(start, deleteCount, ...Array.from(newSubstr));
    } else {
        arr.splice(start, deleteCount);
    }

    // 3. Join the array back into a string
    return arr.join('');
}




function list_intersection(arr1,arr2) {
    // 1. Create a Set from the first array for fast lookups.
    const set1 = new Set(arr1);

    // 2. Filter the second array, keeping only elements present in the set.
    const intersection = arr2.filter(item => set1.has(item));

    // 3. (Optional) Convert the result to a Set and back to an Array to ensure unique values.
    // This is only necessary if the result should not contain duplicates even if they exist in both originals.
    return [...new Set(intersection)];
}


function list_union(arr1,arr2) {
    const union = [...new Set([...arr1, ...arr2])];
    return union
}

function list_difference(arr1,arr2) {
    const set2 = new Set(arr2);
    const filtered = arr1.filter((item) => {
        if ( set2.has(item) ) return false
        return true
    })
    return filtered
}



function sort_object_by_value(obj) {
    let kys = Object.keys(obj)
    kys.sort((a,b) => {
        return -(obj[a] - obj[b])
    })
    //
    let sorted = {}
    //
    for ( let ky of kys ) {
        sorted[ky] = obj[ky]
    }
    //
    return sorted
}



function sort_object_by_keys(obj) {
    //
    let kys = Object.keys(obj)
    kys.sort()
    //
    let sorted = {}
    //
    for ( let ky of kys ) {
        sorted[ky] = obj[ky]
    }
    //
    return sorted
}



/**
 * 
 * @param {string} defstr 
 * @returns {string}
 */
function normalize_css_def_str(defstr) {
    defstr = defstr.replaceAll(/\s\s+/g,' ')
    defstr = defstr.replaceAll('\n','')
    return defstr
}


/**
 * 
 * @param {Array} salient 
 * @returns {Array}
 */
function normalize_css_def_str_array(cssarray) {
    for ( let i = 0; i < cssarray.length; i++ ) {
        let line = cssarray[i]
        line = normalize_css_def_str(line)
        line = line.replaceAll('))',')')
        if ( line[0] != '@') {
            line = line.replace('}}','}')
        }
        line = line.replaceAll(/;\s+\}/g,';}')
        cssarray[i] = line
    }
    return cssarray
}

function normalize_css_def_str_all(salient) {
    for ( let ky in salient ) {
        let css_array = salient[ky]
        salient[ky] = normalize_css_def_str_array(css_array)
    }
    return salient
}

/**
 * 
 * @param {string} defstr 
 */
function parse_out_css_def_key(defstr) {
    //
    let parsed = defstr.split('{',2)
    return parsed[0].trim()
}


let PhIOtjDr_is_custom = {
}

function remove_custom_decls_array(salient) {
    salient = salient.filter((line) => {
        if ( line.indexOf("PhIOtjDr_") >= 0 ) {
            let p = PhIOtjDr_is_custom[line]
            PhIOtjDr_is_custom[line] = p ? p+1 : 1
            return false
        }
        return true
    })
    return salient
}

/**
 * 
 * @param {*} salient 
 */
function remove_custom_decls(salient) {
    for ( let ky in salient ) {
        let css_array = salient[ky]
        salient[ky] = remove_custom_decls_array(css_array)
    }
    return salient
}



const salient_keys = [ "element", "identified", "class", "control" ]


class ColorFixing {
    constructor() {
        this.putils = new ParseUtils()
        this.flags = { "element" : "el", "identified" : "id", "class" : "cl", "control" : "ctrl" }
        this.hex_recognizer = /#([0-9a-fA-F]{3,8})/
    }


    /**
     * 
     * @param {string} cssdef 
     * @param {number} i 
     * @returns {string|boolean}
     */
    get_start_hex(cssdef,i) {
        let chck = cssdef.substring(i,i+10)
        let did_chck = this.hex_recognizer.exec(chck)
        if ( did_chck ) {
            return did_chck[0]
        }
        return false
    }


    is_gradient_definition(cssdef,i) {
        let end_of_def = cssdef.indexOf(';',i)
        let maybe_grad_txt = (end_of_def > 0) ? cssdef.substring(i,end_of_def) : cssdef.substring(i)
        if ( maybe_grad_txt.length ) {
            if ( maybe_grad_txt.indexOf('gradient') >= 0 ) return true
        }
        return false
    }


    named_color(cword) {
        if ( g_color_names.indexOf(cword) >= 0 ) {
            return true
        }
        return false
    }


    /**
     * 
     * (AI assist)
     * @param {string} cssdef 
     * @param {number} i 
     * @returns {string} -- first alpha word of the string
     */
    extract_word(cssdef,i) {
        const match = cssdef.substring(i).match(/^[a-zA-Z]+/);
        // If a match is found, return it. Otherwise, return an empty string or null.
        return match ? match[0] : '';
    }


    /**
     * 
     * @param {string} var_fodder 
     * @returns {string}
     */
    cleanup(var_fodder) {
        let vf = var_fodder.trim()
        vf = vf.replace(/\s+/g,'_')
        vf = vf.replace(/\W/g,"")
        return vf
    }

    /**
     * Same for both rbg and rbga
     * 
     * @param {string} cssdef 
     * @param {number} i 
     * @returns {string}
     */
    extract_rgb_parameters(cssdef,i) {
        let str = cssdef.substring(i,cssdef.lastIndexOf(')')+1)
        let params = this.putils.extract_nested(str,'(',')')
        return params
    }
    
    /**
     * 
     * @param {string} cssdef 
     * @param {number} i 
     */
    extract_gradient(cssdef,i = 0) {
        let nextsemi = cssdef.indexOf(';',i)
        let predef = nextsemi > 0 ? cssdef.substring(i,nextsemi) : cssdef.substring(i)

        let pari = predef.indexOf('(')
        //
        let parstart = predef.substring(pari)
        predef = predef.substring(0,pari)
        let params = this.putils.extract_nested(parstart,'(',')')
        return predef + params
    }


    extract_gradient2(cssdef) {

        let pari = cssdef.indexOf('(')
        //
        let parstart = cssdef.substring(pari)
        let predef = cssdef.substring(0,pari)

        let offset = cssdef.indexOf(predef)

        let params = this.putils.extract_nested(parstart,'(',')')
        return [offset,predef + params]
    }



    /**
     * 
     * @param {string} str 
     * @returns {object}
     */
    color_cases(str) {
        if ( this.is_gradient_definition(str) ) {
            let [offset,gradient_def] = this.extract_gradient2(str)
            return {
                "name" : gradient_def,
                "index" : offset,
                "length" : gradient_def.length
            }
        } else if ( str.indexOf('rgb') >= 0 ) {
            let offset = str.indexOf('rgb')
            if ( str.indexOf('rgba') >= 0 ) {
                let rgba_parameters = this.extract_rgb_parameters(str,4)
                let rgba_def = `rgba${rgba_parameters}`
                return({
                    "name" : rgba_def,
                    "index" : offset,
                    "length" : rgba_def.length
                })
            } else {
                let rgb_parameters = this.extract_rgb_parameters(str,3)
                let rgb_def = `rgb${rgb_parameters}`
                return({
                    "name" : rgb_def,
                    "index" : offset,
                    "length" : rgb_def.length
                })
            }
        } else if ( str.indexOf('#') >= 0) {
            let offset = str.indexOf('#')
            let hexvalue = this.get_start_hex(str,offset)
            if ( hexvalue ) {
                return({
                    "name" : hexvalue,
                    "index" : offset,
                    "length" : hexvalue.length
                })
            }
        } else {
            let color_name = this.extract_word(str)
            if ( this.named_color(color_name) ) {
                return ({
                    "name" : color_name,
                    "index" : 0,
                    "length" : color_name.length
                })
            }
        }
        return false 
    }


    /**
     * 
     * @param {string} cssdef 
     * @param {number} offset 
     * @returns {Array}
     */
    locate_colors(field_defs) {
        let color_list = []
        field_defs = field_defs.replace('}','').trim().split(';')
        let targets = field_defs.map((el,index) => {
            if ( el.length > 0 && el.indexOf(':') > 0 ) {
                let parts = el.trim().split(':')
                parts = parts.map((el) => { return el.trim()})
                return { "check" : true, "i" : index, "parts" : parts }
            } else {
                return { "check" : false, "i" : index, "def"  : el }
            }
        })
        //
        for ( let target of targets ) {
            if ( target.check ) {
                let parts = target.parts
                target.useage = parts[0]
                target.value = parts[1]
                delete target.parts
                target.color = this.color_cases(parts[1])
            }
        }
        
        for ( let i = 0; i < targets.length; i++ ) {
            let target = targets[i]
            if ( target.check && target.color ) {
                target.make_var = true
                let varsub = `var(--$$PLACE_VAR_HERE$$)`
                target.original_value = target.value
                target.value = stringSplice(target.value,target.color.index,target.color.length,varsub)
            } else {
                target.make_var = false
            }
            //
            color_list.push(target)
        }

        return color_list
    }

    reduce_fodder(var_fodder) {
        let vf = this.cleanup(var_fodder)
        return vf.substring(0,Math.min(20,vf.length))
    }

    eliminate_overlap(rvf,print_ky) {
        if ( rvf.indexOf(print_ky) === 0 ) {
            return ""
        }
        for ( let i = 0; i < print_ky.length; i++ ) {
            if ( rvf[i] !== print_ky[i] ) {
                return print_ky.substring(i)
            }
        }
        return print_ky
    }

    /**
     * 
     * @param {string} b 
     * @param {string} cssdef 
     * @param {Array} vname_keys 
     * @param {object} all_vars -- for collecting
     * @returns {string}
     */
    make_def_abstraction(b,cssdef,vname_keys,all_vars) {
        let [flag,ky] = vname_keys

        let var_fodder = cssdef.substring(0,cssdef.indexOf('{'))

        let print_ky = this.cleanup(ky)

        let varstem = `${flag}_` // `${flag}${b}_`
//
// console.log("1",varstem)
// console.log("2",var_fodder)
// console.log(cssdef)
// console.log("--------------------------------------------------------------------------")

        let def_lines = this.locate_colors(cssdef.substring(var_fodder.length + 1).trim())

        let final_def = ""

        for ( let df of def_lines ) {
            if ( df.make_var ) {
                let rvf = this.reduce_fodder(var_fodder)
                //
                print_ky = "" // this.eliminate_overlap(rvf,print_ky)
                //
                let vname = varstem + print_ky + rvf + df.useage

                if ( df.color.name.indexOf("-webkit") === 0 ) {
                    vname += "_wk"
                }
                vname = vname.replace('-','_')

                all_vars[`--${vname}`] = df.color.name
                let value = df.value.replace("$$PLACE_VAR_HERE$$",vname)
                final_def += `\t${df.useage}: ${value};\n`
            } else {
                if ( df.useage && (df.value !== undefined) ) {
                    final_def += `\t${df.useage}: ${df.value};\n`
                } else {
                    final_def += df.def
                }
            }
        }

        let final = var_fodder + '{\n' + final_def + '}\n'
        return final
    }



    look_for_base_color(cssdef) {
        for ( let cname of g_color_names ) {
            if ( cssdef.indexOf(cname) > 0 ) {
                return true
            }
        }
        return false
    }


    /**
     * 
     * @param {string} cssdef 
     * @returns {boolean}
     */
    has_color_use(cssdef) {
        if ( cssdef.indexOf('#') >= 0 ) {
            if ( cssdef[0] === '#' ) {
                return this.has_color_use(cssdef.substring(1))
            } else {
                return true
            }
        } else if ( cssdef.indexOf('color') >= 0 ) {
            return true
        } else if ( cssdef.indexOf('gradient') > 0 ) {
            return true
        } else if ( cssdef.indexOf('rgb') > 0 ) {
            return true
        } else if ( this.look_for_base_color(cssdef) ) {
            return true
        }
        return false
    }


    /**
     * 
     * @param {object} all_vars 
     * @returns {object}
     */
    sort_by_values(all_vars) {
        //
        let kys = Object.keys(all_vars)
        kys.sort((k1,k2) => {
            let v1 = all_vars[k1]
            let v2 = all_vars[k2]
            if ( v1 > v2 ) {
                return 1
            } else if ( v2 > v1 ) {
                return -1
            }
            return 0
        })
        //
        let newtable = {}
        for ( let ky of kys ) {
            newtable[ky] = all_vars[ky]
        }
        return newtable
    }


    // /**
    //  * 
    //  * @param {object} css_data 
    //  */
    // infer_variables(css_data) {
    //     let classified = structuredClone(css_data.classified)
    //     //
    //     let batches = [
    //         classified.classified.element,
    //         classified.classified.identified,
    //         classified.classified.class,
    //         classified.classified.control
    //     ]
    //     let flags = ["el", "id", "cl", "ctrl"]
    //     //
    //     let all_vars = {}
    //     //
    //     for ( let k = 0; k < 4; k++ ) {
    //         let batch = batches[k]
    //         let flag = flags[k]
    //         for ( let ky in batch ) {
    //             let list = batch[ky].list
    //             let b = 0
    //             for ( let i = 0; i < list.length; i++ ) {
    //                 let cssdef = list[i]
    //                 if ( this.has_color_use(cssdef) ) {
    //                     cssdef = this.make_def_abstraction(++b,cssdef,[flag,ky],all_vars)
    //                     list[i] = cssdef
    //                 }
    //             }
    //         }
    //     }
    //     //
    //     let all_vars_sorted = this.sort_by_values(all_vars)
    //     //
    //     return {all_vars, all_vars_sorted, classified}
    // }


    /**
     * 
     * @param {string} ky 
     * @param {Array} css_array 
     * @returns {Array} 
     */
    color_collecting_variable_inference(ky,css_array,all_vars) {
        let flag = this.flags[ky]
        if ( typeof flag === "string" ) {
            let list = [].concat(css_array)
            let b = 0
            for ( let i = 0; i < list.length; i++ ) {
                let cssdef = list[i]
                if ( this.has_color_use(cssdef) ) {
                    cssdef = this.make_def_abstraction(++b,cssdef,[flag,ky],all_vars)
                    list[i] = cssdef
                }
            }
            return list
        }
        return []
    }


    /**
     * 
     * @param {object} salient 
     * @returns {object}
     */
    normalize_basic_colors(salient) {
        let all_vars = {}
        for ( let ky in salient ) {
            if ( ky === "control" ) continue
            let css_array = salient[ky]
            salient[ky] = this.color_collecting_variable_inference(ky,css_array,all_vars)
        }
        return { css_dat : salient, all_vars }
    }

}




let g_color_fixer = new ColorFixing()


function top_level_params(parstr) {
    parstr = parstr.trim()
    let n = parstr.length
    let lastp = ""
    let params = []
    let depth = 0
    for ( let i = 0; i < n; i++ ) {
        let c = parstr[i]
        if ( c === ',' && (depth <= 0) ) {
            params.push(lastp)
            lastp = ""
        } else {
            lastp += c
        }
        if ( c === '(' ) { depth++ }
        if ( c === ')' ) { depth-- }
    }
    params.push(lastp)
    return params
}


function lift_nested_colors(all_vars) {
    //
    let vars_update = {}
    for ( let ky in all_vars ) {
        let val = all_vars[ky]
        if ( val.indexOf("gradient") > 0 ) {
            let pos = val.indexOf('(') + 1
            let checkstr = val.substring(pos,val.lastIndexOf(')'))
            let params = top_level_params(checkstr)
            //
            params = params.map((p) => {
                p = p.trim()
                return g_color_fixer.color_cases(p)
            })
            //
            params = params.filter((p) => {
                return p
            })

            let val_update = val
            let n = params.length
            for ( let i = 0; i < n; i++ ) {
                let p = params[i]
                let vname = ky + `_c${i}`
                let gval = p.name
                val_update = val_update.replace(gval,`var(${vname})`)
                vars_update[vname] = gval
            }
            all_vars[ky] = val_update
            //
        } 
    }
    //
    for ( let [vname,val] of Object.entries(all_vars) ) {
        vars_update[vname] = val
    }
    //
    return vars_update
}





let analysis_source = "/home/richard/GitHub/alphas/copious-software-dev-manager/plugins/snippet_finder/css_output"

const fs = require('fs');

let files_list = fs.readdirSync(analysis_source)

// START HERE

let file_data = {}
for ( let file of files_list ) {
    //
    let css_data = fs.readFileSync(`${analysis_source}/${file}`).toString()
    css_data = JSON.parse(css_data)
    //
    let salient =  Object.fromEntries(salient_keys.map(item => [item, css_data[item]]))
    salient = normalize_css_def_str_all(salient)
    salient = remove_custom_decls(salient)
    salient = g_color_fixer.normalize_basic_colors(salient)
    file_data[file] = salient
    //
}

let big_intersection = Object.fromEntries(salient_keys.map(item => [item,[]]))
//
// start the big intersection with a big union
for ( let file in file_data ) {
    let css_dat = file_data[file].css_dat
    for ( let ky of salient_keys ) {
        let current_intr = big_intersection[ky]
        let css_type_entries = css_dat[ky]
        big_intersection[ky] = list_union(current_intr,css_type_entries)
    }
}


//console.dir(big_intersection)

for ( let file in file_data ) {
    let css_dat = file_data[file].css_dat
    for ( let ky of salient_keys ) {
        if ( ky === "control" ) {
            continue
        }
        let current_intr = big_intersection[ky]
        let css_type_entries = css_dat[ky]
        //console.log(css_type_entries.length)
        if ( css_type_entries.length > 8 ) {
            big_intersection[ky] = list_intersection(current_intr,css_type_entries)
            css_dat.ignored = false
        } else {
            css_dat.ignored = true
        }
    }
}

//console.dir(big_intersection)


// WRITE A FILE THAT HAS MANY SHARED DEFS ... not necessarily optimal
let out_file = "./css/shared_styles.css"


let out_css = ""
for ( let css_list of Object.values(big_intersection) ) {
    out_css += css_list.join("\n\n") + "\n"
}

fs.writeFileSync(out_file,out_css)



// MORE FIGURING


for ( let file in file_data ) {
    let css_data = file_data[file].css_dat
    let salient =  Object.fromEntries(salient_keys.map(item => [item, css_data[item]]))

    css_data.diff = salient
    for ( let ky of salient_keys ) {
        let final_intr = big_intersection[ky]
        let css_type_entries = css_data[ky]
        css_data.diff[ky] = css_data.diff[ky].concat(list_difference(css_type_entries,final_intr))
    }
}

//
// This makes the the map of css keys to a list of all definitions for the same key
//

let redefs = Object.fromEntries(salient_keys.map(item => [item, {}]))
let defs_dict = {}
let other_controls = {}
let media_rules = {}
//
for ( let file in file_data ) {
    let css_data = file_data[file].css_dat
    for ( let ky of salient_keys ) {
        if ( ky === "control" ) continue;
        let css_type_entries = css_data[ky]
        for ( let entry of css_type_entries ) {
            entry = normalize_css_def_str(entry)
            if ( defs_dict[entry] === undefined ) {
                defs_dict[entry] = 1
                let defkey = parse_out_css_def_key(entry)
                let cssset = redefs[ky]     // redefs
                if ( cssset[defkey] ) {
                    cssset[defkey].defs.push(entry)
                    let ftrack = cssset[defkey].files[entry]
                    if ( ftrack ) {
                        ftrack.push(file)
                    } else {
                        cssset[defkey].files[entry] = [file]
                    }
                } else {
                    cssset[defkey] = { "defs" : [entry], "files" : {} }
                    cssset[defkey].files[entry] = [file]
                }
            } else {
                defs_dict[entry]++
                let defkey = parse_out_css_def_key(entry)
                let cssset = redefs[ky]     // redefs
                if ( cssset[defkey] ) {
                    //cssset[defkey].defs.push(entry)
                    let ftrack = cssset[defkey].files[entry]
                    if ( ftrack ) {
                        ftrack.push(file)
                    } else {
                        cssset[defkey].files[entry] = [file]
                    }
                } else {
                    cssset[defkey] = { "defs" : [entry], "files" : {} }
                    cssset[defkey].files[entry] = [file]
                }
            }
        }
    }
    let ky = "control"
    let css_type_entries = css_data[ky]
    for ( let entry of css_type_entries ) {
        if ( entry.startsWith("@media") ) {
            // console.log(file,entry)
            let def_start = entry.indexOf('{') + 1
            let defs_part = entry.substring(def_start).trim()
            let media_control = entry.substring(0,def_start-1).trim()
            // console.log(defs_part)
            let mrule_ky = defs_part.substring(0,defs_part.indexOf('{')).trim()
            let def = defs_part.substring(defs_part.indexOf('{'),defs_part.indexOf('}'))
            if ( media_rules[mrule_ky] ) {
                if ( media_rules[mrule_ky][def] ) {
                    if (  media_rules[mrule_ky][def][media_control] ) {
                        media_rules[mrule_ky][def][media_control].push(file)
                    } else {
                        media_rules[mrule_ky][def][media_control] = [file]
                    }
                } else {
                    media_rules[mrule_ky][def] = {}
                    media_rules[mrule_ky][def][media_control] = [file]
                }
            } else {
                media_rules[mrule_ky] = {}
                media_rules[mrule_ky][def] = {}
                media_rules[mrule_ky][def][media_control] = [file]
            }
            //
            // media_rules
        } else {
            let p = other_controls[entry]
            other_controls[entry] = p ? (p+1) : 1
        }
    }
}

console.dir(other_controls)
console.dir(media_rules,{ depth : 6 })

defs_dict = sort_object_by_value(defs_dict)
let similarity_grouping = sort_object_by_keys(defs_dict)


console.log("----------------------------------")
console.dir(redefs,{ depth : 4})
console.log("----------------------------------")
console.dir(defs_dict)
console.log("----------------------------------")
console.dir(similarity_grouping)



console.log("----------------------------------")
console.log("----------------------------------")
console.dir(PhIOtjDr_is_custom)

let all_vars = {}
for ( let file in file_data ) {
    //
    let f_all_vars = file_data[file].all_vars
    //
    for ( let [ky,value] of Object.entries(f_all_vars) ) {
        all_vars[ky] = value
    }
}


all_vars = lift_nested_colors(all_vars)

console.log("----------------------------------")
console.log("----------------------------------")

let var_txt = vars_to_text(all_vars)

console.log(var_txt)
